version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase
      - maven clean package
    post-build:
      commands:
        - echo Build completed successfully
artifacts:
  files:
    - target/product-serviced.jar
  discard-paths: yes
